name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs: 
  Explore-GitHub-Actions:
    container: 
      image: docker.io/library/adamsrunner:1.1.0  
    runs-on: arc-runner-set
    steps:
    - name: Show Payload
      run: | 
        echo " github.event.sender: ${{ github.event.sender }} "
        echo " github.event.inputs: ${{ github.event.inputs }} "
        echo " github.event.repository: ${{ github.event.repository }} "
        echo " github.event.enterprise: ${{ github.event.enterprise }} "
        echo " github.event.ref: ${{ github.event.ref }} "
        echo " github.event.installation: ${{ github.event.installation }} "
    - name: Call Custom Action
      uses: adamwaterson/create-repo-test@main
      with:        
        Response: From ARC demo repo
    - name: checkout repo
      uses: actions/checkout@v4   
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      env: 
        DOTNET_INSTALL_DIR: /home/runner/deps
    - name: Restore dotnet nuget packages
      run: dotnet restore --locked-mode
