name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs: 
  Explore-GitHub-Actions:
    container: 
      image: docker.io/library/adamsrunner:1.1.0  
    runs-on: arc-runner-set
    steps:
    - name: Show Payload
      run: | 
        echo " fromJSON (github.event) : ${{fromJSON(github.event)}} "
        echo " github.event.sender.id: ${{ github.event.sender.id }} "
        echo " github.event.sender.email: ${{ github.event.sender.email }} "
        echo " github.event.sender.login: ${{ github.event.sender.login }} "
        echo " github.event.sender.name: ${{ github.event.sender.name }} "
        echo " github.event.sender.node_id: ${{ github.event.sender.node_id }} "
        echo " github.event.inputs: ${{ github.event.inputs }} "
        echo " github.event.repository.master_branch: ${{ github.event.repository.master_branch }} "
        echo " github.event.enterprise.name: ${{ github.event.enterprise.name }} "
        echo " github.event.enterprise.id: ${{ github.event.enterprise.id }} "
        echo " github.event.enterprise.node_id: ${{ github.event.enterprise.node_id }} "        
        echo " github.event.ref: ${{ github.event.ref }} "
        echo " github.event.installation.id: ${{ github.event.installation.id }} "
        echo " github.event.installation.node_id: ${{ github.event.installation.node_id }} "
    - name: Call Custom Action
      uses: adamwaterson/create-repo-test@main
      with:        
        Response: From ARC demo repo
    - name: checkout repo
      uses: actions/checkout@v4   
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      env: 
        DOTNET_INSTALL_DIR: /home/runner/deps
    - name: Restore dotnet nuget packages
      run: dotnet restore --locked-mode
#
