name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - name: checkout repo
      uses: actions/checkout@v4   
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
      env: 
        DOTNET_INSTALL_DIR: /home/runner/deps
    - name: Restore dotnet nuget packages
      run: dotnet restore
